export type ViewMode = 'exterior' | 'xray' | 'exploded';
export type SystemId = 'engine' | 'transmission' | 'suspension' | 'brakes' | 'aero' | 'chassis';
export type Finish = { name: string; color: string; swatch: string };
export const finishes: Finish[] = [
  { name: 'Liquid Silver', color: '#a8b0b3', swatch: '#afb5b8' },
  { name: 'Obsidian Black', color: '#22272c', swatch: '#34383e' },
  { name: 'Glacier White', color: '#e0e2de', swatch: '#e0e2de' },
  { name: 'Ember Red', color: '#802724', swatch: '#a33c33' },
];
export const systems: { id: SystemId; number: string; name: string; label: string; title: string; description: string; detail: string; metric: string; unit: string; fact: string; position: [number, number, number] }[] = [
  { id: 'engine', number: '01', name: 'Powertrain', label: 'THE HEART OF THE R1', title: 'Six cylinders.\nOne singular feeling.', description: 'A 4.0-liter twin-turbo flat-six turns combustion into a relentless, beautifully balanced surge of power.', detail: 'Opposing pistons move in horizontally arranged banks, keeping the center of gravity low. Two turbochargers use exhaust energy to compress incoming air, helping the engine produce more power from every combustion cycle.', metric: '620', unit: 'HP', fact: '4.0L TWIN-TURBO FLAT-SIX', position: [1.35, 1.05, 0.15] },
  { id: 'transmission', number: '02', name: 'Transmission', label: 'POWER, WITHOUT INTERRUPTION', title: 'The next gear.\nAlready waiting.', description: 'An 8-speed dual-clutch transmission keeps the engine in its sweet spot, with the next ratio preselected.', detail: 'One clutch manages odd-numbered gears; the other handles even-numbered gears. As one opens, the other closes, transferring power to the rear wheels with minimal interruption. An electronically controlled differential varies locking to manage traction.', metric: '8', unit: 'SPEED', fact: 'DUAL-CLUTCH · REAR-WHEEL DRIVE', position: [0.5, 0.65, -0.15] },
  { id: 'suspension', number: '03', name: 'Suspension', label: 'CONNECTED TO EVERY CORNER', title: 'Read the road.\nRewrite the limits.', description: 'Adaptive damping and rear-wheel steering bring composure to fast corners and agility to tight ones.', detail: 'Electronically controlled dampers adjust resistance as the road changes. At low speeds, the rear wheels steer against the fronts to tighten the turning circle. At higher speeds, they steer in the same direction for greater stability.', metric: '4', unit: 'CORNERS', fact: 'ADAPTIVE DAMPING · REAR STEERING', position: [-1.6, 0.9, 0.92] },
  { id: 'brakes', number: '04', name: 'Braking', label: 'CONFIDENCE IS A FORCE', title: 'Extraordinary pace.\nAbsolute composure.', description: 'A performance braking system turns speed into heat, with ventilation that keeps the response consistent.', detail: 'Fixed calipers squeeze pads against ventilated discs. Friction slows each wheel, while internal channels carry cooling air through the rotor. ABS modulates pressure when a wheel approaches lock-up, helping preserve steering control.', metric: '4', unit: 'DISCS', fact: 'VENTILATED PERFORMANCE BRAKES', position: [-1.65, 0.52, 1.08] },
  { id: 'aero', number: '05', name: 'Aerodynamics', label: 'SHAPED BY THE INVISIBLE', title: 'The air moves.\nSo does the R1.', description: 'Active aerodynamics adapt the car’s silhouette to balance straight-line efficiency and high-speed stability.', detail: 'The rear wing changes its angle to influence downforce and drag. A sculpted underbody and rear diffuser guide airflow beneath the chassis. Select Track mode to see the wing rise into its high-downforce position.', metric: '326', unit: 'KM/H', fact: 'ACTIVE REAR WING · REAR DIFFUSER', position: [2.12, 1.12, 0] },
  { id: 'chassis', number: '06', name: 'Chassis', label: 'STRENGTH IN EVERY FIBER', title: 'Less mass.\nMore connection.', description: 'A carbon composite structure creates a rigid foundation for precise steering, suspension, and power delivery.', detail: 'Layers of carbon fiber carry loads along carefully selected paths. Bonded structures form a stiff central cell, helping suspension geometry remain consistent under cornering loads while limiting the mass the car has to accelerate.', metric: 'R1', unit: 'MONOCOQUE', fact: 'CARBON COMPOSITE ARCHITECTURE', position: [-0.15, 0.9, 0] },
];
export const specifications = [
  ['Engine', '4.0L twin-turbo flat-six'], ['Maximum power', '620 HP'], ['Peak torque', '720 Nm'],
  ['Transmission', '8-speed dual-clutch'], ['Drivetrain', 'Rear-wheel drive'], ['0–100 km/h', '2.9 seconds'],
  ['Top speed', '326 km/h'], ['Chassis', 'Carbon composite'], ['Steering', 'Rear-wheel steering'],
  ['Suspension', 'Adaptive damping'], ['Differential', 'Electronically controlled'], ['Aerodynamics', 'Active rear wing'],
];
